language: python
python:
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpocketsphinx-dev libsphinxbase-dev
install:
  - pip install cython
script:
  - sh ./mk-psext
