cmake_minimum_required(VERSION 2.8)

if (QT4_FOUND)
    include(UseQt4)
else(QT4_FOUND)
    message(FATAL_ERROR "SpeechControl requires Qt4 in order to be built.")
endif(QT4_FOUND)

set(SPCHCNTRL_COMPILE_FLAGS "--std=c++0x")
set(SPCHCNTRL_COMPILE_FLAGS_DEBUG "-Wall -Wextra -Wabi -Wctor-dtor-privacy -Wformat -Wunused -O0 -ggdb")
set(SPCHCNTRL_COMPILE_DEFINITIONS ${QT_DEFINITIONS})
set(SPCHCNTRL_CMAKE_DIR "${CMAKE_INSTALL_PREFIX}/share/cmake/SpeechControl")
set(SPCHCNTRL_CMAKE_INSTALL_DIR "${CMAKE_MODULE_PATH}")
set(SPCHCNTRL_DATA_DIR "${CMAKE_INSTALL_PREFIX}/share/speechcontrol")
set(SPCHCNTRL_DATA_CONTENT_DIR "${SPCHCNTRL_DATA_DIR}/contents")
set(SPCHCNTRL_LIB_DIR "${CMAKE_INSTALL_PREFIX}/lib")
set(SPCHCNTRL_BIN_DIR "${CMAKE_INSTALL_PREFIX}/bin")
set(SPCHCNTRL_LOCALE_DIR "${CMAKE_INSTALL_PREFIX}/share/locale")
set(SPCHCNTRL_INCLUDE_DIR "${CMAKE_INSTALL_PREFIX}/include/speechcontrol")
set(SPCHCNTRL_LISTENERS_LIB_INSTALL_DIR "${SPCHCNTRL_LIB_DIR}")
set(SPCHCNTRL_LISTENERS_SPEC_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/share/speechcontrol/listeners")
set(SPCHCNTRL_DOC_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/share/doc")

########### Some automatics ###################
set(CMAKE_USE_RELATIVE_PATHS ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
